# Generated by Django 4.2.1 on 2023-05-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Questions', models.CharField(max_length=200)),
                ('Answers', models.IntegerField()),
                ('Start_date', models.TimeField()),
                ('End_date', models.TimeField()),
                ('status', models.CharField(choices=[('inactive', 'inactive'), ('active', 'active'), ('finished', 'finished')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Write', models.CharField(max_length=100)),
            ],
        ),
    ]
