# Generated by Django 4.2.1 on 2023-05-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.CharField(blank=True, max_length=300)),
                ('intensity', models.CharField(blank=True, max_length=300)),
                ('sector', models.CharField(blank=True, max_length=300)),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('insight', models.CharField(blank=True, max_length=300)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('region', models.CharField(blank=True, max_length=300)),
                ('start_year', models.CharField(blank=True, max_length=300)),
                ('impact', models.CharField(blank=True, max_length=300)),
                ('added', models.CharField(blank=True, max_length=300)),
                ('publishe', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(blank=True, max_length=300)),
                ('relevance', models.CharField(blank=True, max_length=300)),
                ('pestle', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('likelihood', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DetailsNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(blank=True, max_length=300)),
                ('end_year', models.CharField(blank=True, max_length=300)),
                ('intensity', models.CharField(blank=True, max_length=300)),
                ('relevance', models.CharField(blank=True, max_length=300)),
                ('likelihood', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
